name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Change to project directory
        run: cd workspace/jeju-travel-planner

      - name: Install dependencies
        run: |
          cd workspace/jeju-travel-planner
          npm ci

      - name: Build Next.js
        run: |
          cd workspace/jeju-travel-planner
          npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./workspace/jeju-travel-planner/out
